baseURL = 'https://g.mgmavlca.com/'
languageCode = 'en-us'
title = 'MGMAVLCA'

[minify]
    minifyOutput = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true
                title = true

[menus]
    [[menus.main]]
        name = 'Form'
        pageRef = '/form'
        weight = 1
    [[menus.main]]
        name = 'Upload'
        pageRef = '/upload'
        weight = 2
    [[menus.main]]
        name = 'Grades'
        pageRef = '/grades'
        weight = 3
    [[menus.main]]
        name = 'Records'
        pageRef = '/records'
        weight = 4
    [[menus.main]]
        name = 'Notices'
        pageRef = '/notices'
        weight = 5
    [[menus.main]]
        name = 'See'
        pageRef = '/see'
        weight = 6
    [[menus.main]]
        name = 'About'
        pageRef = '/about'
        weight = 7