baseURL = 'https://mgmavlca.com/'
languageCode = 'en-us'
title = 'MGMAVLCA'

[minify]
    minifyOutput = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true
                title = true

[menus]
    [[menus.main]]
        name = 'Form'
        pageRef = '/form'
        weight = 1
    [[menus.main]]
        name = 'Upload'
        pageRef = '/upload'
        weight = 2
    [[menus.main]]
        name = 'Docs'
        pageRef = '/docs'
        weight = 3
    [[menus.main]]
        name = 'Complain'
        pageRef = '/complain'
        weight = 4